name: New Resource Group Request
description: Request a new resource group in DTS-INNOVATION-PROD.
title: "[RG Request]: "
labels: [ "request" ]
type: request
body:
  - type: markdown
    attributes:
      value: |
        Please populate the fields below to request a new resource group in DTS-INNOVATION-PROD. If you have any questions, please raise a PlatOps Help Ticket.
  - type: input
    id: owner
    attributes:
      label: Owner's Name
      description: Full name of the resource group Owner. This will be used to set up
        notifications and will act as a point of contact for the resource group.
      placeholder: ex. Joe Blogs
    validations:
      required: true
  - type: input
    id: owner_email
    attributes:
      label: Owner's Email Address
      description: Email address of the resource group Owner. This will be used to set
        up notifications and will act as a point of contact for the resource
        group.
      placeholder: ex. user.name@justice.gov.uk
    validations:
      required: true
  - type: input
    id: owning_team
    attributes:
      label: Owning Team
      description: Name of the team that will own the resource group.
      placeholder: ex. DTS Platform Operations
    validations:
      required: false
  - type: input
    id: end_date
    attributes:
      label: Expiry Date
      description: Date when the Proof of Concept is expected to end. In the format
        YYYY-MM-DD.
      placeholder: "2026-12-31"
    validations:
      required: true
